name: Wireshark Plugin

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: |
        sudo apt-get update && sudo apt-get install cmake build-essential wireshark-dev libgcrypt-dev gnutls-dev libgtest-dev
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: build
      run: cmake --build build/ --target all
    - name: check
      run: |
        cd build
        ctest -V
